### ISSUE TITLE
"Require interaction" option not respected

### ISSUE THREAD

**Issue by enisoc** [PagerDuty/chrome-notifier#21] opened 2020-05-18 18:01 UTC
Thanks for this extension! It's been working great for me except for this minor issue:

The notifications always require interaction, even if I uncheck "Require interaction to dismiss notification?" and save the config.

I eventually figured out through trial and error that the problem, for my system at least, seems to be the hard-coded non-zero priority:

https://github.com/PagerDuty/chrome-notifier/blob/02176fcc6087945da247ee8b6d8fa242a87d4869/pd-notifier/background/pd-notifier.js#L255

Here's the test case that I pasted into the Chrome dev console in the context of this extension's options page:

```js
chrome.notifications.create("test0", {
    type: "basic",
    iconUrl: chrome.extension.getURL("images/icon-256.png"),
    title: "test 0",
    message: "priority 0",
    priority: 0,
    requireInteraction: false
});

chrome.notifications.create("test1", {
    type: "basic",
    iconUrl: chrome.extension.getURL("images/icon-256.png"),
    title: "test 1",
    message: "priority 1",
    priority: 1,
    requireInteraction: false
});

chrome.notifications.create("test2", {
    type: "basic",
    iconUrl: chrome.extension.getURL("images/icon-256.png"),
    title: "test 2",
    message: "priority 2",
    priority: 2,
    requireInteraction: false
});
```

On my system, only the one set to `priority: 0` respects the `requireInteraction: false` setting. The others require interaction regardless of the setting.

It could be something specific to my shell, if that priority value is being passed along by Chrome, but I haven't found any shell-level settings that cause `requireInteraction` to be respected for PD notifications. Could we perhaps get an option to customize the priority value to work around this?

Extension version: 0.22
Chrome version: Version 81.0.4044.138 (Official Build) (64-bit)
OS: Ubuntu 20.04
Shell: KDE Plasma Shell

**Comment by richadams** [comment] 2020-06-02 20:47
First of all, I just wanted to thank you for what has to be the most in-depth and useful bug report I've ever received. Not just on an open-source project, but on any project ever. You got the line with the issue, test cases, and your environment versions and so on. Thank you so much!

As for the problem itself, in a quick test, I can reproduce the behaviour you describe. 

The documentation of course mentions none of this, that would've been too easy. https://developer.chrome.com/apps/richNotifications

> Notifications can be assigned a priority between -2 to 2. Priorities < 0 are shown in the ChromeOS notification center, and produce an error on other platforms. Priority 0 is the default priority. Priorities > 0 are shown for increasing duration and more high priority notifications can be displayed in the system tray.

I'll make an update to set the priority to 0 so that the feature works again. I'll also add a new context menu option to make testing of notifications a bit easier while I'm at it.

Thanks again for the great bug report!

**Comment by richadams** [comment] 2020-06-02 20:51
This will be fixed in version 0.23, which I'll push to the Chrome store later today. Thanks again for the report!

**Closed as completed** 2020-06-02 20:51 UTC
Labels: typo / bug

**Comment by enisoc** [comment] 2020-06-02 21:44
Thanks for the fix! Looking forward to the release, and to logging in each morning with a clean slate. :)

**Comment by richadams** [comment] 2020-06-02 21:58
Looks like Google are requiring reviews of all extensions now, and it can take "several weeks". So while the update has been submitted to the store, I've no idea how long it will take to appear. Hopefully not too long, but if you need the update earlier you can manually install the tagged release from here https://github.com/PagerDuty/chrome-notifier/releases/tag/0.23.

Thanks again!

**Comment by enisoc** [comment] 2020-06-03 16:51
The update went live and my browser auto-updated. I can confirm the fix worked for me. Thanks again!
